import React, { useState, useEffect, useRef } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { MessageSquare, X, Send, Mic, MicOff, Volume2, VolumeX, ThumbsUp, ThumbsDown, Phone, ArrowUpRight, Sparkles, Bot, User, RotateCcw, CheckCircle2, Minimize2, Maximize2, MapPin, Target, Navigation, Calculator, Scale } from 'lucide-react';
import { ChatMessage, ChatApiResponse, SentimentType } from '../types';
import { BudgetPlannerCard } from './BudgetPlannerCard';
import { ComparisonMatrixCard } from './ComparisonMatrixCard';
const CHAT_API_URL=(import.meta as any).env?.VITE_CHAT_API_URL||'https://idurlccrarznnnqixxsd.supabase.co/functions/v1/studenthubhelp-chat';
const SUPABASE_ANON_KEY=(import.meta as any).env?.VITE_SUPABASE_ANON_KEY||'';
interface ChatWidgetProps { onDiagnosisUpdate?: (diagnosis:any,userMessage:string)=>void; onLeadCaptured?: (lead:any)=>void; initialOpen?: boolean; }
const QUICK_TOPICS=[{label:'Monthly Budget Planner',query:'Mera monthly student budget plan banao',topic:'Student Monthly Budget Planner'},{label:'Compare Active Hostels',query:'Mere city me active hostels compare karo',topic:'Live Hostel Comparison'},{label:'Find Hostels',query:'Mere liye active hostels dikhao',topic:'Hostel Discovery'},{label:'Find Tiffin',query:'Active tiffin services dikhao',topic:'Tiffin Discovery'},{label:'Find Jain Food',query:'Active Jain food tiffin services dikhao',topic:'Jain Food Discovery'},{label:'Find Libraries',query:'Active libraries dikhao',topic:'Library Discovery'},{label:'Girls Hostel Safety',query:'Active girls hostel listings me available safety details batao',topic:'Girls Hostel Safety'},{label:'Budget Options',query:'Mere budget ke according active listings dikhao',topic:'Budget Discovery'},{label:'Contact Support',query:'StudentHubHelp support contact details batao',topic:'Support'},{label:'Search by Area',query:'Mere area ke active listings dikhao',topic:'Area Discovery'}];
export const ChatWidget:React.FC<ChatWidgetProps>=({onDiagnosisUpdate,onLeadCaptured,initialOpen=true})=>{
 const [isOpen,setIsOpen]=useState(initialOpen); const [isExpanded,setIsExpanded]=useState(false); const [inputText,setInputText]=useState(''); const [isLoading,setIsLoading]=useState(false); const [isListening,setIsListening]=useState(false); const [isSpeakingEnabled,setIsSpeakingEnabled]=useState(true); const [unreadCount,setUnreadCount]=useState(0); const [recentLeadAlert,setRecentLeadAlert]=useState<string|null>(null); const [activeTopic,setActiveTopic]=useState<string|null>(null);
 const [sessionId]=useState(()=>{try{return crypto.randomUUID();}catch{return `chat-${Date.now()}-${Math.random().toString(36).slice(2,10)}`;}});
 const [messages,setMessages]=useState<ChatMessage[]>([{id:'welcome-1',sender:'bot',text:'Namaste! Main StudentHubHelp AI Assistant hoon.\n\nAap hostel, tiffin, library, cafe, bookstore, area, budget ya support ke baare me pooch sakte hain. Listing recommendations live active data par based hongi.\n\nAap kis topic se start karna chahte hain?',timestamp:new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}),diagnosis:{intent:'Welcome / Onboarding',primaryTopic:'Student Accommodation & Services Discovery',topicDirectAnswer:'Aapka requested topic pehle handle kiya jayega.',topicPriorityReason:'Initial onboarding guidance with Topic Priority enabled.',userNeedSummary:'Initial student guidance with full AI topic priority.',sentiment:'positive',suggestedFollowUps:['Active hostels dikhao','Active tiffin services dikhao','Active libraries dikhao','Support details batao']}}]);
 const messagesEndRef=useRef<HTMLDivElement>(null); const recognitionRef=useRef<any>(null);
 const scrollToBottom=()=>messagesEndRef.current?.scrollIntoView({behavior:'smooth'});
 useEffect(()=>{if(isOpen){scrollToBottom();setUnreadCount(0);}},[messages,isOpen]);
 useEffect(()=>{const SpeechRecognition=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(SpeechRecognition){const recognition=new SpeechRecognition();recognition.continuous=false;recognition.interimResults=false;recognition.lang='hi-IN';recognition.onresult=(event:any)=>{const transcript=event.results[0][0].transcript;setInputText(prev=>prev?`${prev} ${transcript}`:transcript);setIsListening(false);};recognition.onerror=()=>setIsListening(false);recognition.onend=()=>setIsListening(false);recognitionRef.current=recognition;}},[]);
 const toggleSpeechRecognition=()=>{if(!recognitionRef.current){alert('Browser voice recognition is not supported in this browser. Please use Chrome, Edge or Safari.');return;}if(isListening){recognitionRef.current.stop();setIsListening(false);}else{try{recognitionRef.current.start();setIsListening(true);}catch{setIsListening(false);}}};
 const speakText=(text:string)=>{if(!isSpeakingEnabled||!window.speechSynthesis)return;window.speechSynthesis.cancel();const plainText=text.replace(/[*_#`[\]()]/g,' ').replace(/\n+/g,'. ');const utterance=new SpeechSynthesisUtterance(plainText);utterance.rate=1;utterance.pitch=1;const voices=window.speechSynthesis.getVoices();const preferredVoice=voices.find(v=>v.lang.includes('hi')||v.lang.includes('IN'))||voices.find(v=>v.lang.includes('en'))||voices[0];if(preferredVoice)utterance.voice=preferredVoice;window.speechSynthesis.speak(utterance);};
 const handleSendMessage=async(textToSend?:string,topicOverride?:string)=>{const text=(textToSend||inputText).trim();if(!text||isLoading)return;const topicToPrioritize=topicOverride||activeTopic;const userMessage:ChatMessage={id:`user-${Date.now()}`,sender:'user',text,timestamp:new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})};setMessages(prev=>[...prev,userMessage]);setInputText('');setIsLoading(true);try{const history=messages.slice(-6).map(m=>({role:m.sender==='user'?('user' as const):('model' as const),text:m.text}));if(!SUPABASE_ANON_KEY)throw new Error('Missing VITE_SUPABASE_ANON_KEY. Add the public Supabase anon/publishable key to the Vite build environment.');const controller=new AbortController();const timeoutId=window.setTimeout(()=>controller.abort(),20000);let res:Response;try{res=await fetch(CHAT_API_URL,{method:'POST',headers:{'Content-Type':'application/json',apikey:SUPABASE_ANON_KEY,Authorization:`Bearer ${SUPABASE_ANON_KEY}`},body:JSON.stringify({message:text,history,preferredTopic:topicToPrioritize,sessionId}),signal:controller.signal});}finally{window.clearTimeout(timeoutId);}if(!res.ok){let detail='';try{const errorBody=await res.json();detail=errorBody?.error||errorBody?.message||'';}catch{}throw new Error(detail||`Chat request failed (${res.status})`);}const data:ChatApiResponse=await res.json();if(!data||typeof data.reply!=='string'||!data.reply.trim())throw new Error('Chat backend returned an invalid response.');const botMessage:ChatMessage={id:`bot-${Date.now()}`,sender:'bot',text:data.reply,timestamp:new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}),diagnosis:{intent:data.intent,primaryTopic:data.primaryTopic,topicDirectAnswer:data.topicDirectAnswer,topicPriorityReason:data.topicPriorityReason,userNeedSummary:data.userNeedSummary,sentiment:data.sentiment as SentimentType,suggestedFollowUps:data.suggestedFollowUps||[]},recommendedProperties:data.recommendedProperties||data.recommendations||[],budgetPlan:data.budgetPlan,comparisonMatrix:data.comparisonMatrix};setMessages(prev=>[...prev,botMessage]);if(data.capturedLead){setRecentLeadAlert('Lead captured from this conversation.');onLeadCaptured?.(data.capturedLead);}onDiagnosisUpdate?.(botMessage.diagnosis,text);setActiveTopic(null);speakText(data.reply);}catch(err:any){const errorMessage:ChatMessage={id:`bot-error-${Date.now()}`,sender:'bot',text:err?.name==='AbortError'?'The response took too long. Please try again.':(err?.message||'Chat service is temporarily unavailable.'),timestamp:new Date().toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})};setMessages(prev=>[...prev,errorMessage]);}finally{setIsLoading(false);}};
 const resetChat=()=>{setMessages([]);setActiveTopic(null);setRecentLeadAlert(null);};
 return <div className="relative">{/* Existing chatbot UI continues here */}</div>;
};
