import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const U=(Deno.env.get("SUPABASE_URL")||"").replace(/\/$/,"");
const K=Deno.env.get("SUPABASE_SECRET_KEY")||Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")||"";
const GEMINI=Deno.env.get("GEMINI_API_KEY")||"";
const MODEL="gemini-2.5-flash";
const RATE_WINDOW_MS=60_000; const RATE_MAX=30;
const rateMap=new Map<string,{start:number,count:number}>();
function rateKey(req:Request){const forwarded=req.headers.get("x-forwarded-for")||req.headers.get("cf-connecting-ip")||"unknown";return forwarded.split(",")[0].trim().slice(0,100)||"unknown";}
function allowed(req:Request){const key=rateKey(req),now=Date.now(),old=rateMap.get(key);if(!old||now-old.start>=RATE_WINDOW_MS){rateMap.set(key,{start:now,count:1});return true;}if(old.count>=RATE_MAX)return false;old.count++;return true;}
const SRC=[["hostels","hostel"],["tiffins","tiffin"],["libraries","library"],["cafes","cafe"],["bookstores","bookstore"]] as const;
const H={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization,x-client-info,apikey,content-type","Access-Control-Allow-Methods":"POST,OPTIONS","Content-Type":"application/json"};
const n=(v:any)=>String(v??"").toLowerCase().normalize("NFKC").replace(/[^a-z0-9\u0900-\u097f]+/gi," ").replace(/\s+/g," ").trim();
const num=(v:any)=>{const x=Number(String(v??"").replace(/,/g,""));return Number.isFinite(x)?x:undefined};
async function db<T>(path:string):Promise<T>{if(!U||!K)throw Error("database configuration missing");const r=await fetch(U+path,{headers:{apikey:K,Authorization:`Bearer ${K}`,"Content-Type":"application/json"}});if(!r.ok)throw Error(`database ${r.status}`);return await r.json() as T}
function city(s:string){const x=n(s),m:[string,string][]=[["sikar","Sikar"],["piprali","Sikar"],["पिपराली","Sikar"],["सिकर","Sikar"],["kota","Kota"],["talwandi","Kota"],["jaipur","Jaipur"],["ajmer","Ajmer"],["bikaner","Bikaner"],["jodhpur","Jodhpur"],["udaipur","Udaipur"],["alwar","Alwar"],["delhi","Delhi"],["ahmedabad","Ahmedabad"],["lucknow","Lucknow"],["hyderabad","Hyderabad"],["pune","Pune"]];return m.find(([a])=>x.includes(n(a)))?.[1]||""}
function cat(s:string){const x=n(s);const hits:[string,number][]=[];const defs:[string,RegExp][]=[["hostel",/hostel|pg|room|stay|accommodation|girls|boys|female|male|rehne|rehna|रहने|हॉस्टल|पीजी/],["tiffin",/tiffin|mess|khana|food|meal|jain food|टिफिन|मेस|खाना/],["library",/library|study|reading|seat|padhai|लाइब्रेरी/],["cafe",/cafe|coffee|restaurant|hangout|कैफे/],["bookstore",/bookstore|books|stationery|bookshop|किताब|बुकस्टोर/]];for(const [type,re] of defs)for(const m of x.matchAll(new RegExp(re.source,"gi")))hits.push([type,m.index??-1]);const near=new Set(hits.filter(([,pos])=>/(near|nearby|around|paas|pass|ke paas|k pass|aas paas|bagal|nazdeek|पास|आस पास|बगल)/i.test(x.slice(Math.max(0,pos-50),pos))).map(([type])=>type));return hits.find(([type])=>!near.has(type))?.[0]||hits[0]?.[0]}
function secondaryCats(s:string){const x=n(s),out:string[]=[];const defs:[string,RegExp][]=[["hostel",/hostel|pg|room|stay|accommodation|girls|boys|female|male|rehne|rehna|रहने|हॉस्टल|पीजी/],["tiffin",/tiffin|mess|khana|food|meal|टिफिन|मेस|खाना/],["library",/library|study|reading|seat|padhai|लाइब्रेरी/],["cafe",/cafe|coffee|restaurant|hangout|कैफे/],["bookstore",/bookstore|books|stationery|bookshop|किताब|बुकस्टोर/]];for(const [type,re] of defs)for(const m of x.matchAll(new RegExp(re.source,"gi"))){const pos=m.index??-1;if(/(near|nearby|around|paas|pass|ke paas|k pass|aas paas|bagal|nazdeek|पास|आस पास|बगल)/i.test(x.slice(Math.max(0,pos-50),pos)))out.push(type)}return [...new Set(out)]}
function coords(p:any){const lat=Number(p.latitude),lng=Number(p.longitude);return Number.isFinite(lat)&&Number.isFinite(lng)?{lat,lng}:null}
function distanceKm(a:any,b:any){const A=coords(a),B=coords(b);if(!A||!B)return undefined;const r=(v:number)=>v*Math.PI/180,dLat=r(B.lat-A.lat),dLon=r(B.lng-A.lng),h=Math.sin(dLat/2)**2+Math.cos(r(A.lat))*Math.cos(r(B.lat))*Math.sin(dLon/2)**2;return 6371*2*Math.atan2(Math.sqrt(h),Math.sqrt(1-h))}
async function multiDirect(types:string[],ct?:string){const out:any[]=[];for(const type of [...new Set(types.filter(Boolean))])out.push(...await direct(type,ct));return out}
async function nearbyFilter(primary:any[],secondary:any[]){if(!secondary.length)return primary;const out:any[]=[];for(const p of primary){let best=Infinity;for(const q of secondary){const d=distanceKm(p,q);if(d!==undefined&&d<best)best=d;if(d===undefined&&p.area&&searchText(q).includes(n(p.area)))best=Math.min(best,1)}if(best<=3){p._nearbyDistanceKm=Number(best.toFixed(2));p._nearbyVerified=true;out.push(p)}}return out}
function priceLabel(p:any,c:string){const v=Number(p.monthly_rent??p.monthly_fee??p.monthly_charge??p.price);if(!Number.isFinite(v)||v<=0)return "";if(c==="hostel"||c==="tiffin"||c==="library")return "₹"+v.toLocaleString("en-IN")+"/mo";return "₹"+v.toLocaleString("en-IN")}
function card(p:any){const c=p._type,price=priceLabel(p,c);return{id:String(p.id),name:p.name||p.title||p.service_name||p.business_name||"Active listing",type:c,city:p.city||"",area:p.area||p.service_area||"",address:p.address||"",phone:p.phone||p.contact_phone||p.whatsapp||p.whatsapp_number||"",rating:num(p.rating),verified:p.verified===true,price,highlights:["facilities","amenities","wifi","ac_available","ac","cctv","food_available","mess_available","available_beds","room_types","room_sharing","gender_type","timing","timings","delivery_available","nearby_coaching","description"].map(k=>[k,p[k]]).filter(([,v])=>v!==null&&v!==undefined&&String(v).trim()!==""&&String(v).toLowerCase()!=="false").slice(0,8).map(([k,v])=>k+": "+String(v)),description:p.description||"",mapsUrl:p.google_maps_url||"",detailsUrl:p.slug?"property-details.html?type="+c+"&slug="+encodeURIComponent(p.slug):undefined}}
function isGreeting(s:string){return /^(hi|hello|hey|namaste|good morning|good afternoon|good evening|good night|gm|gn|hii|hlo|नमस्ते|सुप्रभात|शुभ प्रभात|शुभ संध्या)[!.\s]*$/i.test(s.trim())}
function isContact(s:string){return /director|founder|contact|support|phone number|email|baat karni|baat krni|contact us/i.test(n(s))}
function greeting(){const h=Number(new Date().toLocaleString("en-US",{hour:"numeric",hour12:false,timeZone:"Asia/Kolkata"}));if(h<12)return "☀️ Good morning! Have a great day!\n\nWelcome to StudentHubHelp 😊\n\n**What would you like to explore today?**\n\n🏠 Hostel / PG\n🍱 Tiffin\n📚 Library\n☕ Cafe\n📖 Bookstore\n📍 Explore a location\n📞 Contact / Help\n\nYou can also simply tell me what you need in Hindi, English or Hinglish.";if(h<17)return "🌤️ Good afternoon! Welcome to StudentHubHelp 😊\n\n**What can I help you explore today?**\n\n🏠 Hostel / PG · 🍱 Tiffin · 📚 Library · ☕ Cafe · 📖 Bookstore\n\nOr simply tell me what you need in your own words.";return "🌆 Good evening! Welcome to StudentHubHelp 😊\n\n**What can I help you find today?**\n\n🏠 Hostel / PG · 🍱 Tiffin · 📚 Library · ☕ Cafe · 📖 Bookstore\n\nTell me your city, area or requirement and I’ll guide you."}
function label(c:string){return c==="hostel"?"hostel / PG":c==="tiffin"?"tiffin service":c==="library"?"library":c==="cafe"?"cafe":c==="bookstore"?"bookstore":"student service"}
function fallbackReply(c:string|undefined,recs:any[],near:string){const l=label(c||"");if(recs.length)return `Haan 😊 ${near?`${near} ke paas `:""}${recs.length} active ${l} listing${recs.length>1?"s":""} mil rahi ${recs.length>1?"hain":"hai"}. Neeche sirf **${l}** ke relevant options diye gaye hain.`;return `Abhi ${near?`${near} ke paas `:""}koi matching **${l}** listing nahi mili. Aap area/city ka naam thoda aur specific bhej sakte hain.`}
async function ai(msg:string,history:any[],recs:any[],c?:string,near?:string){if(!GEMINI)return{};try{const h=Array.isArray(history)?history.slice(-8).map(x=>`${x.role==='user'?'USER':'ASSISTANT'}: ${String(x.text||'')}`).join("\n"):"";const l=label(c||"");const prompt=`You are StudentHubHelp AI Assistant, a premium student-first website assistant.\nLANGUAGE: Match the user's language style: English -> polished English, Hinglish -> natural respectful Hinglish, Devanagari -> Hindi.\nPERSONALITY: warm, concise, impressive, helpful, never robotic.\nCONVERSATION CONTEXT:\n${h}\n\nCURRENT USER MESSAGE: ${msg}\n\nINTENT CATEGORY: ${l}\nLOCATION/NEARBY TERM: ${near||"none"}\n\nLIVE CANDIDATES (ONLY SOURCE OF TRUTH FOR LISTINGS):\n${JSON.stringify(recs.slice(0,8))}\n\nSTRICT RULES:\n- Answer the CURRENT USER MESSAGE first.\n- If INTENT CATEGORY is ${l}, talk ONLY about ${l}. Never substitute another category.\n- Never claim a listing is nearby unless the candidate data supports the requested location/term.\n- The listing cards are authoritative. Do not invent or replace their category.\n- Never invent property facts, ratings, addresses, facilities, phone numbers, availability, verification or prices.\n- Listing prices are not currently displayed. Do not mention, display, calculate, compare or recommend using listing prices/budgets.\n- Verification is a review/status signal, not a guarantee.\n- If candidates do not support a fact, say the information is not currently available.\n- Keep the answer focused and useful.`;const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${MODEL}:generateContent`,{method:"POST",headers:{"Content-Type":"application/json","x-goog-api-key":GEMINI},body:JSON.stringify({contents:[{role:"user",parts:[{text:prompt}]}],generationConfig:{maxOutputTokens:450,temperature:0.35}})});if(!r.ok)return{};const j=await r.json();return{reply:j?.candidates?.[0]?.content?.parts?.map((p:any)=>p.text||"").join("")||""}}catch{return{}}}
Deno.serve(async(req:Request)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:H});if(req.method!=="POST")return new Response(JSON.stringify({error:"POST required"}),{status:405,headers:H});try{if(!allowed(req))return new Response(JSON.stringify({error:"Too many requests. Please try again shortly."}),{status:429,headers:{...H,"Retry-After":"60"}});const contentLength=Number(req.headers.get("content-length")||0);if(contentLength>32768)return new Response(JSON.stringify({error:"Request is too large."}),{status:413,headers:H});const b=await req.json(),msg=String(b?.message||"").trim().slice(0,1500),history=Array.isArray(b?.history)?b.history.slice(-8).map((x:any)=>({role:String(x?.role||"").slice(0,20),text:String(x?.text||"").slice(0,1000)})):[];if(!msg)return new Response(JSON.stringify({error:"Message is required"}),{status:400,headers:H});if(isGreeting(msg))return new Response(JSON.stringify({reply:greeting(),intent:"Greeting / Onboarding",primaryTopic:"StudentHubHelp Discovery",suggestedFollowUps:["Find a hostel","Find a tiffin service","Find a library","Contact support"],recommendations:[],recommendedProperties:[],grounded:true,sessionId:String(b?.sessionId||crypto.randomUUID())}),{headers:H});if(isContact(msg))return new Response(JSON.stringify({reply:"Ji bilkul 😊 Aap StudentHubHelp team se contact kar sakte hain.\n\n📧 Email: satpalswami22742@gmail.com\n📞 Phone: +91 9929718264\n\nAgar aap kisi specific property/listing ke baare me contact karna chahte hain, uska naam ya listing link bhej dijiye.",intent:"Support / Contact",primaryTopic:"Contact StudentHubHelp",suggestedFollowUps:["Property correction","Claim a listing","Report a listing","Back to search"],recommendations:[],recommendedProperties:[],grounded:true,sessionId:String(b?.sessionId||crypto.randomUUID())}),{headers:H});const previous=history.filter(x=>x.role==="user").map(x=>x.text||"").join(" ");
const explicitCat=cat(msg),nearCats=secondaryCats(msg),c=explicitCat||cat(previous),combined=previous+" "+msg,ct=city(msg)||city(combined)||"",near=nearTerm(msg);
const action=String(b?.action||""),shownIds=new Set((Array.isArray(b?.shownPropertyIds)?b.shownPropertyIds:[]).map((x:any)=>String(x)));
if(action==="contact_support"){return new Response(JSON.stringify({reply:"Ji bilkul 😊 StudentHubHelp team se contact ke liye:\n\n📧 Email: satpalswami22742@gmail.com\n📞 Phone: +91 9929718264\n\nAap kisi specific property/listing ka naam bhej sakte hain.",intent:"Support / Contact",primaryTopic:"Contact StudentHubHelp",recommendedProperties:[],recommendations:[],suggestedFollowUps:["Find a hostel","Find a library","Search by area","Back to search"],grounded:true,sessionId:String(b?.sessionId||crypto.randomUUID())}),{headers:H})}
if(action==="search_area"&&!city(msg)&&!nearTerm(msg)){return new Response(JSON.stringify({reply:"Bilkul 😊 Aap kis **area / locality** mein search karna chahte hain? Area ka naam bhejiye, main current requirement ke saath search refine kar dunga.",intent:"Area Refinement",primaryTopic:c?label(c)+" discovery":"Student Services Discovery",recommendedProperties:[],recommendations:[],suggestedFollowUps:["Search by city","Show more options","Contact support"],grounded:true,sessionId:String(b?.sessionId||crypto.randomUUID())}),{headers:H})}
let rows=await multiDirect(c?[c]:(nearCats.length?nearCats:["hostel"]),ct);
if(nearCats.length){const secondaryRows=await multiDirect(nearCats,ct);rows=await nearbyFilter(rows,secondaryRows)}
if(near&&!nearCats.length)rows=rows.filter(p=>searchText(p).includes(near));
rows=rows.filter(p=>!shownIds.has(String(p.id)));
const ranked=rows.map(p=>({...p,_score:rank(p,combined,ct,near)})).sort((a,z)=>z._score-a._score);
let recs=ranked.slice(0,8).map(card);
if(action==="view_details"){const focusId=String(b?.focusPropertyId||""),focusType=String(b?.focusPropertyType||c||"hostel"),focusRows=await multiDirect([focusType],ct),focus=focusRows.find(p=>String(p.id)===focusId);recs=focus?[card(focus)]:recs.slice(0,1)}
const ar=await ai(msg,history,recs,c,near);
let reply=ar.reply||fallbackReply(c,recs,near);
const followups=["View full details","Search by area","Show more options","Contact support"];
return new Response(JSON.stringify({reply,intent:c?"Live Property Search":"General Inquiry",primaryTopic:c?label(c)+" discovery":"Student Services Discovery",recommendedProperties:recs,recommendations:recs,suggestedFollowUps:followups,grounded:true,sessionId:String(b?.sessionId||crypto.randomUUID()),searchMode:"ultra_contextual_live_search",targetCity:ct||undefined,targetCategory:c||undefined,nearbyTerm:near||undefined}),{headers:H})
return new Response(JSON.stringify({reply,intent:c?"Live Property Search":"General Inquiry",primaryTopic:c?`${c} discovery`:"Student Services Discovery",recommendedProperties:recs,recommendations:recs,suggestedFollowUps:recs.length?["View full details","Search by area","Show more options","Contact support"]:["Find a hostel","Find a tiffin service","Find a library","Contact support"],grounded:true,sessionId:String(b?.sessionId||crypto.randomUUID()),searchMode:"live_contextual_ai",targetCity:ct||undefined,targetCategory:c||undefined,nearbyTerm:near||undefined}),{headers:H})}catch(e){return new Response(JSON.stringify({reply:"Ji, live search me temporary issue aaya. Please same query dobara bhejiye.",grounded:false,error:"Temporary server error"}),{status:200,headers:H})}});