import React, { useEffect, useMemo, useState } from 'react';
import { CalendarDays, Clock3, Mail, MapPin, Phone, Search, UserRound, X, CheckCircle2 } from 'lucide-react';
import { Appointment } from '../types';
import { fetchAppointments, updateAppointment } from '../lib/supabase';

const statusStyles: Record<string,string> = {
  pending:'bg-amber-500/10 text-amber-300 border-amber-500/25',
  contacted:'bg-sky-500/10 text-sky-300 border-sky-500/25',
  confirmed:'bg-emerald-500/10 text-emerald-300 border-emerald-500/25',
  rescheduled:'bg-violet-500/10 text-violet-300 border-violet-500/25',
  completed:'bg-teal-500/10 text-teal-300 border-teal-500/25',
  cancelled:'bg-rose-500/10 text-rose-300 border-rose-500/25',
  rejected:'bg-slate-500/10 text-slate-300 border-slate-500/25',
};
const fmtDate=(v?:string)=>{if(!v)return '—';try{return new Date(v+'T00:00:00').toLocaleDateString('en-IN',{day:'2-digit',month:'short',year:'numeric'});}catch{return v;}};
const fmtDateTime=(v?:string)=>{if(!v)return '—';try{return new Date(v).toLocaleString('en-IN',{day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'});}catch{return v;}};

export const AppointmentsView: React.FC = () => {
  const [rows,setRows]=useState<Appointment[]>([]),[loading,setLoading]=useState(true),[query,setQuery]=useState(''),[status,setStatus]=useState('all'),[selected,setSelected]=useState<Appointment|null>(null),[saving,setSaving]=useState(false),[note,setNote]=useState('');
  const load=async()=>{setLoading(true);try{setRows(await fetchAppointments())}catch(e){console.error(e)}finally{setLoading(false)}};
  useEffect(()=>{void load()},[]);
  const filtered=useMemo(()=>rows.filter(r=>{const q=query.trim().toLowerCase();const hay=[r.appointment_code,r.name,r.phone,r.email,r.purpose,r.appointment_type].filter(Boolean).join(' ').toLowerCase();return(!q||hay.includes(q))&&(status==='all'||String(r.status||'pending').toLowerCase()===status)}),[rows,query,status]);
  const counts=useMemo(()=>({pending:rows.filter(r=>r.status==='pending').length,contacted:rows.filter(r=>r.status==='contacted').length,confirmed:rows.filter(r=>r.status==='confirmed').length,completed:rows.filter(r=>r.status==='completed').length}),[rows]);
  const save=async(patch:Partial<Appointment>)=>{if(!selected)return;setSaving(true);try{const updated=await updateAppointment(selected.id,{...patch,admin_note:patch.admin_note??note});setRows(p=>p.map(r=>String(r.id)===String(updated.id)?updated:r));setSelected(updated);setNote(updated.admin_note||'')}catch(e){alert((e as any)?.message||'Unable to update appointment.')}finally{setSaving(false)}};
  return <div className="space-y-6">
    <div className="flex flex-col lg:flex-row lg:items-end lg:justify-between gap-4"><div><div className="text-[10px] uppercase tracking-[.22em] text-amber-400 font-extrabold">Platform Operations</div><h1 className="text-3xl md:text-4xl font-serif font-extrabold text-white mt-1">Appointments</h1><p className="text-sm text-slate-400 mt-2">Website + chatbot appointment requests in one secure workspace.</p></div><button onClick={()=>void load()} className="px-4 py-2.5 rounded-xl border border-amber-500/25 bg-amber-500/5 text-amber-300 text-xs font-extrabold">Refresh</button></div>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{[['Pending',counts.pending],['Contacted',counts.contacted],['Confirmed',counts.confirmed],['Completed',counts.completed]].map(([l,c])=><div key={String(l)} className="rounded-2xl border border-slate-800 bg-[#08142b] p-4"><div className="text-[10px] uppercase tracking-widest text-slate-500 font-bold">{String(l)}</div><div className="text-2xl font-black text-white mt-1">{String(c)}</div></div>)}</div>
    <div className="rounded-2xl border border-slate-800 bg-[#08142b] p-4 flex flex-col md:flex-row gap-3"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-500"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, phone, email, purpose or appointment ID" className="w-full pl-9 pr-3 py-2.5 rounded-xl bg-[#050b1a] border border-slate-700 text-xs text-white outline-none focus:border-amber-400"/></div><select value={status} onChange={e=>setStatus(e.target.value)} className="md:w-48 px-3 py-2.5 rounded-xl bg-[#050b1a] border border-slate-700 text-xs text-white"><option value="all">All statuses</option>{['pending','contacted','confirmed','rescheduled','completed','cancelled','rejected'].map(s=><option key={s} value={s}>{s[0].toUpperCase()+s.slice(1)}</option>)}</select></div>
    <div className="rounded-2xl border border-slate-800 overflow-hidden bg-[#07132c]">{loading?<div className="p-10 text-center text-xs text-slate-500">Loading appointments…</div>:filtered.length===0?<div className="p-12 text-center text-sm text-slate-500">No appointment requests found.</div>:<div className="overflow-x-auto"><table className="w-full text-left"><thead className="bg-slate-900/70"><tr>{['Appointment','Student','Purpose','Preferred','Mode','Status','Created'].map(x=><th key={x} className="px-4 py-3 text-[9px] uppercase tracking-widest text-slate-500 font-extrabold">{x}</th>)}</tr></thead><tbody>{filtered.map(r=><tr key={String(r.id)} onClick={()=>{setSelected(r);setNote(r.admin_note||'')}} className="border-t border-slate-800 hover:bg-white/[.03] cursor-pointer"><td className="px-4 py-4"><div className="text-xs font-black text-amber-300">{r.appointment_code||('#'+r.id)}</div><div className="text-[10px] text-slate-500 mt-1">{r.appointment_type||'General Consultation'}</div></td><td className="px-4 py-4"><div className="text-xs font-bold text-white">{r.name||'—'}</div><div className="text-[10px] text-slate-500">{r.phone||''}</div></td><td className="px-4 py-4"><div className="text-xs text-slate-300 max-w-[230px] truncate">{r.purpose||'—'}</div></td><td className="px-4 py-4"><div className="text-xs font-bold text-white">{fmtDate(r.preferred_date)}</div><div className="text-[10px] text-slate-500">{r.preferred_time||'—'}</div></td><td className="px-4 py-4 text-xs text-slate-300">{r.mode||'—'}</td><td className="px-4 py-4"><span className={'inline-flex px-2 py-1 rounded-full border text-[9px] font-extrabold uppercase '+(statusStyles[String(r.status||'pending').toLowerCase()]||statusStyles.pending)}>{r.status||'pending'}</span></td><td className="px-4 py-4 text-[10px] text-slate-500">{fmtDateTime(r.created_at)}</td></tr>)}</tbody></table></div>}</div>
    {selected&&<div className="fixed inset-0 z-[900] bg-black/70 flex items-center justify-center p-4" onClick={()=>setSelected(null)}><div className="w-full max-w-2xl max-h-[90vh] overflow-y-auto rounded-3xl border border-amber-500/20 bg-[#07132c] shadow-2xl" onClick={e=>e.stopPropagation()}>
      <div className="p-5 border-b border-slate-800 flex items-start justify-between"><div><div className="text-[10px] uppercase tracking-widest text-amber-400 font-extrabold">Appointment Request</div><h2 className="text-2xl font-serif font-extrabold text-white mt-1">{selected.appointment_code||('#'+selected.id)}</h2><div className="text-xs text-slate-500 mt-1">Created {fmtDateTime(selected.created_at)} · via {selected.source||'website'}</div></div><button onClick={()=>setSelected(null)} className="p-2 rounded-xl bg-white/5 text-slate-400"><X className="w-5 h-5"/></button></div>
      <div className="p-5 space-y-5"><div className="grid md:grid-cols-2 gap-3">{[[UserRound,'Name',selected.name],[Phone,'Phone',selected.phone],[Mail,'Email',selected.email],[MapPin,'Mode',selected.mode],[CalendarDays,'Preferred date',fmtDate(selected.preferred_date)],[Clock3,'Preferred time',selected.preferred_time]].map(([I,l,v])=><div key={String(l)} className="rounded-xl border border-slate-800 bg-slate-900/30 p-3"><div className="flex items-center gap-2 text-[10px] uppercase tracking-wider text-slate-500 font-bold"><I className="w-3.5 h-3.5 text-amber-400"/>{String(l)}</div><div className="text-sm text-white mt-1 break-words">{String(v||'—')}</div></div>)}</div>
      <div className="rounded-2xl border border-slate-800 bg-slate-900/30 p-4"><div className="text-[10px] uppercase tracking-wider text-slate-500 font-bold">Purpose</div><div className="text-sm text-slate-200 mt-2 whitespace-pre-wrap">{selected.purpose||'—'}</div>{selected.message&&<><div className="text-[10px] uppercase tracking-wider text-slate-500 font-bold mt-4">Additional message</div><div className="text-sm text-slate-300 mt-2 whitespace-pre-wrap">{selected.message}</div></>}</div>
      <div className="grid md:grid-cols-2 gap-3"><div><label className="text-[10px] uppercase tracking-wider text-slate-500 font-bold">Status</label><select disabled={saving} value={selected.status||'pending'} onChange={e=>void save({status:e.target.value})} className="mt-2 w-full px-3 py-2.5 rounded-xl bg-[#050b1a] border border-slate-700 text-xs text-white">{['pending','contacted','confirmed','rescheduled','completed','cancelled','rejected'].map(s=><option key={s} value={s}>{s[0].toUpperCase()+s.slice(1)}</option>)}</select></div><div><label className="text-[10px] uppercase tracking-wider text-slate-500 font-bold">Confirmed date</label><input type="date" value={selected.confirmed_date||''} onChange={e=>setSelected({...selected,confirmed_date:e.target.value})} className="mt-2 w-full px-3 py-2.5 rounded-xl bg-[#050b1a] border border-slate-700 text-xs text-white"/></div><div><label className="text-[10px] uppercase tracking-wider text-slate-500 font-bold">Confirmed time</label><input value={selected.confirmed_time||''} onChange={e=>setSelected({...selected,confirmed_time:e.target.value})} placeholder="4:30 PM" className="mt-2 w-full px-3 py-2.5 rounded-xl bg-[#050b1a] border border-slate-700 text-xs text-white"/></div></div>
      <div><label className="text-[10px] uppercase tracking-wider text-slate-500 font-bold">Admin note</label><textarea value={note} onChange={e=>setNote(e.target.value)} rows={4} placeholder="Internal note…" className="mt-2 w-full px-3 py-2.5 rounded-xl bg-[#050b1a] border border-slate-700 text-xs text-white resize-y"/></div>
      <div className="flex flex-wrap gap-2"><button disabled={saving} onClick={()=>void save({status:'contacted',admin_note:note})} className="px-4 py-2.5 rounded-xl bg-sky-500/10 border border-sky-500/25 text-sky-300 text-xs font-extrabold">Mark Contacted</button><button disabled={saving} onClick={()=>void save({status:'confirmed',confirmed_date:selected.confirmed_date||selected.preferred_date,confirmed_time:selected.confirmed_time||selected.preferred_time,admin_note:note})} className="px-4 py-2.5 rounded-xl bg-emerald-500/10 border border-emerald-500/25 text-emerald-300 text-xs font-extrabold">Confirm Appointment</button><button disabled={saving} onClick={()=>void save({status:'rescheduled',confirmed_date:selected.confirmed_date||null,confirmed_time:selected.confirmed_time||null,admin_note:note})} className="px-4 py-2.5 rounded-xl bg-violet-500/10 border border-violet-500/25 text-violet-300 text-xs font-extrabold">Reschedule</button><button disabled={saving} onClick={()=>void save({status:'completed',admin_note:note})} className="px-4 py-2.5 rounded-xl bg-teal-500/10 border border-teal-500/25 text-teal-300 text-xs font-extrabold">Completed</button><button disabled={saving} onClick={()=>void save({status:'cancelled',admin_note:note})} className="px-4 py-2.5 rounded-xl bg-rose-500/10 border border-rose-500/25 text-rose-300 text-xs font-extrabold">Cancel</button><button disabled={saving} onClick={()=>void save({admin_note:note,confirmed_date:selected.confirmed_date||null,confirmed_time:selected.confirmed_time||null})} className="px-4 py-2.5 rounded-xl border border-slate-700 text-slate-300 text-xs font-extrabold">Save Details</button></div>
      <div className="text-[10px] text-slate-500 flex items-center gap-2"><CheckCircle2 className="w-3.5 h-3.5"/>Status changes are stored in appointment history automatically.</div>
      </div></div></div>}
  </div>;
};