import React from 'react';
import { SectionTab } from '../types';
import { PieChart, LineChart, Users, GraduationCap, Briefcase, Building2, Hotel, Utensils, BookOpen, Coffee, Store, Inbox, Handshake, AlertOctagon, ShieldCheck, CalendarCheck, Star, AlertTriangle, Images, Crown, MapPin, Bell, History, Sliders, Tags, UserCheck, Power, Bot } from 'lucide-react';

interface SidebarProps { currentTab: SectionTab; onSelectTab: (tab: SectionTab) => void; badges: { listingRequests:number; claimRequests:number; unverifiedProperties:number; verificationRequests:number; bookings:number; reviews:number; reports:number; }; onLogout:()=>void; isOpenMobile:boolean; onCloseMobile:()=>void; }

export const Sidebar: React.FC<SidebarProps> = ({ currentTab,onSelectTab,badges,onLogout,isOpenMobile,onCloseMobile }) => {
  const navItemClass=(tab:SectionTab)=>{const isActive=currentTab===tab;return `w-full flex items-center justify-between px-3 py-2.5 rounded-xl text-xs font-bold transition-all ${isActive?'bg-amber-500/15 text-amber-300 border border-amber-500/30 shadow-sm':'text-slate-300 hover:text-white hover:bg-slate-800/60 border border-transparent'}`;};
  const badgeClass='text-[10px] font-extrabold px-2 py-0.5 rounded-full bg-amber-500/10 text-amber-300 border border-amber-500/25';
  const item=(tab:SectionTab,label:string,Icon:any,badge?:number)=><button onClick={()=>{onSelectTab(tab);onCloseMobile();}} className={navItemClass(tab)}><span className="flex items-center gap-2.5"><Icon className="w-4 h-4 text-amber-400"/><span>{label}</span></span>{badge&&badge>0?<span className={badgeClass}>{badge}</span>:null}</button>;
  const content=<aside className="w-64 h-full max-h-screen bg-[#07132c] border-r border-amber-500/20 flex flex-col overflow-hidden select-none"><div className="p-5 border-b border-slate-800/90 flex items-center gap-3 shrink-0"><div className="w-10 h-10 rounded-xl bg-gradient-to-br from-amber-400 via-amber-500 to-amber-600 text-slate-950 flex items-center justify-center font-serif font-black text-lg">SH</div><div><div className="font-serif font-extrabold text-sm tracking-wide bg-gradient-to-r from-amber-200 via-amber-300 to-amber-500 bg-clip-text text-transparent">StudentHubHelp</div><div className="text-[10px] text-emerald-400 font-bold flex items-center gap-1 mt-0.5"><span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-ping"/>DIRECTOR ONLINE</div></div></div><nav className="p-3 space-y-1 text-xs font-medium flex-1 overflow-y-auto custom-scrollbar">
    {item('overview','Overview Dashboard',PieChart)}{item('analytics','Analytics & Graphs',LineChart)}{item('user-management','User Management',Users)}{item('students','Students',GraduationCap)}{item('owners','Owners',Briefcase)}
    <div className="pt-3 mt-3 border-t border-slate-800"><div className="text-[9px] uppercase tracking-widest text-slate-400 font-extrabold px-3 py-1">Directory & Listings</div>{item('properties','All Properties',Building2)}{item('hostels','Hostels & PGs',Hotel)}{item('tiffins','Tiffin & Mess',Utensils)}{item('libraries','24/7 Libraries',BookOpen)}{item('cafes','Student Cafes',Coffee)}{item('bookstores','Bookstores',Store)}</div>
    <div className="pt-3 mt-3 border-t border-slate-800"><div className="text-[9px] uppercase tracking-widest text-slate-400 font-extrabold px-3 py-1">Platform Operations</div>{item('listing-requests','Listing Requests',Inbox,badges.listingRequests)}{item('claim-requests','Claim Requests',Handshake,badges.claimRequests)}{item('unverified-properties','Unverified Queue',AlertOctagon,badges.unverifiedProperties)}{item('verification','Verification Center',ShieldCheck,badges.verificationRequests)}{item('bookings','Bookings / Admissions',CalendarCheck,badges.bookings)}{item('reviews','Reviews Moderation',Star,badges.reviews)}{item('reports','Reports & Grievance',AlertTriangle,badges.reports)}{item('media','Media & Gallery',Images)}{item('featured','Featured Listings',Crown)}</div>
    <div className="pt-3 mt-3 border-t border-slate-800"><div className="text-[9px] uppercase tracking-widest text-slate-400 font-extrabold px-3 py-1">System & Settings</div>{item('areas','Areas & Locations',MapPin)}{item('notifications','Notifications Log',Bell)}{item('activity','Activity & Audit Trail',History)}{item('settings','System Settings',Sliders)}{item('categories','Category Config',Tags)}<button onClick={()=>{onSelectTab('admin');onCloseMobile();}} className={navItemClass('admin')}><span className="flex items-center gap-2.5"><Bot className="w-4 h-4 text-amber-400"/><span>AI Chatbot & CRM</span></span></button></div>
  </nav><div className="p-3 border-t border-slate-800"><button onClick={onLogout} className="w-full flex items-center gap-2.5 px-3 py-2.5 rounded-xl text-xs font-bold text-slate-300 hover:text-rose-300 hover:bg-rose-500/10"><Power className="w-4 h-4"/><span>Logout</span></button></div></aside>;
  return <>{content}{isOpenMobile&&<div className="fixed inset-0 z-[500] bg-black/60 md:hidden" onClick={onCloseMobile}/>}</>;
};
